version: '3'
services:
    chrome:
        image: selenium/standalone-chrome
        ports:
            - "4444:4444"
            - "5900:5900"

    rpa-challenge:
        image: pikut/rpa-challenge:v2
        depends_on:
            - chrome
        restart: on-failure
