version: '3'
services:
    chrome:
        image: selenium/standalone-chrome
        ports:
            - "4444:4444"
            - "5900:5900"

    rpa-challenge:
        build: .
        depends_on:
            - chrome
